language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
services:
- mysql
before_script:
- mysql --user=root --execute='CREATE DATABASE IF NOT EXISTS test;'
- mysql --user=root --execute='GRANT ALL ON test.* TO test@localhost;'
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: IcyIsiv/DmUOtXlJoUF1D5PHnjK/kCrDr2BQCm9iLxp6or66Ti0Jeq/+q748Jm8B3hogysFu/8qYxvzmJ09FUiJZ3VyH1PIB9rj2oWKOHqj23XQApqgdDbfWgYOoBkm7maACekfD7xNNSesfc4ilrZuqEWyX+hCyf/zpgpgDfsg=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: T8I2SFTXHTEWg5CADcpPCU5qL0xGS1pGEawNDCvxcZn4Luw0EEgBdWw40cX38hvrSwsdJmZWQ7gAxIZ7ZgzEW5Y7CMp6e5sex6CNvQVZTP927NKlZnkWOjjDydmDokdyXrKGQewsfrdct6jSsTlsWdPtro5fvPB9azZ5wo4246Q=
sudo: false
