language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: LNxZdo4tcS8ZqoLCczqNejIDvT+6BxueUvRJDp1MIPJfblNlGshl4ORaejtiHg/4j4ANP+2f63GbZEXapF4J87zMJFbJiQ+MBOTA8IWBdb7xvBmFa5MZqdGdNuq5dGd5fTubRWV2FNKTAcCHBVU6J9VgESj4MfXVDvD+aMI5LdM=
notifications:
  email: false
  slack:
    secure: UVFYTBR1G/3vo+GwkBSV/z9GgWFhjHA5cpCVunY4gv3tPFvTgjHyUCRrfc/BFhITvX15upH6+7QnMtKEGfWeN8t7EgJSqSIowl8bUHnlq90v51tjSLdquIR1Vi3mFPQL3YdJUKNdFfzsRTT9CxYQ+XJKSdPzCPu4CHb+pGIAo+Y=
sudo: false
